# https://github.com/lldap/lldap/blob/main/docs/install.md#with-docker

volumes:
  lldap_data:
    driver: local

services:
  lldap:
    image: lldap/lldap:stable
    ports:
      - 17170:17170
    volumes:
      - lldap_data:/data
    environment:
      - LLDAP_JWT_SECRET=secret
      - LLDAP_KEY_SEED=secret
      - LLDAP_LDAP_BASE_DN=dc=ascyii,dc=de
      - LLDAP_LDAP_USER_PASS=admin
