services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - data/data:/data
      - data/letsencrypt:/etc/letsencrypt

volumes:
  data: {}
  
networks:
  npm:
    external: true
