- name: List available CT images
  hosts: pvemsi
  vars:
    search: ""
  tasks:
    - name: Get available CT images
      ansible.builtin.command: >-
        pvesh get /nodes/{{ ansible_facts.hostname }}/aplinfo --output-format json
      changed_when: false
      register: aplinfo

    - name: Print available CT images
      ansible.builtin.debug:
        msg: "{{ available_ct_images }}"
      vars:
        search_query: "[?contains(template, '{{ search }}')].template"
        available_ct_images: "{{ aplinfo.stdout | from_json | json_query(search_query) }}"

    - name: Get PCIE devices list
      ansible.builtin.command: >-
        pvesh get /nodes/{{ ansible_facts.hostname }}/hardware/pci --output-format json
      changed_when: false
      register: pciedevices

    - name: Print available PCIE devices list
      ansible.builtin.debug:
        msg: "{{ available_pcie_devices }}"
      vars:
        search_query: "[?contains(vendor_name, '{{ search }}')]"
        available_pcie_devices: "{{ pciedevices.stdout | from_json | json_query(search_query) }}"
